name: CI

on: [push, pull_request, workflow_dispatch]

jobs:
  test:
    name: "Node.js ${{ matrix.node-version }} on ${{ matrix.os }}"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        node-version: 16

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Run build
        run: npm run build

      - name: Run Server Test
        run: npm run test:server

      - name: Run E2E Test
        uses: GabrielBB/xvfb-action@v1.6
        with:
          run: npm run test
